### ISSUE TITLE
OS Error: Connection refused

### ISSUE THREAD

**Issue by lorenacimpean** [KazuCocoa/appium_dart#38]
The following SocketException was thrown running a test:
OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58270

static var localServer = Uri.parse('http://127.0.0.1:4723/wd/hub/');

I think there's something wrong with how the URI from createDriver is parsed, somewhere it assigns a different port than the one from the URI and then at some point it starts incrementing it by 2 on every run. 

I also tried running the tests from your example and I get the same exception. 
Can you please have a look?
Also, it would be really helpful if you could create a detailed guide on how to set up the driver because it's not very intuitive.

**Comment by KazuCocoa** [comment]
Could you share below information?
I'll run the example tonight. Potentially some dependencies got changes since my last test.

1. How to start an appium server on your local?
2. Dependencies

I only did `pub get` and run as https://github.com/KazuCocoa/appium_dart/tree/main/example to run this client, so possibly I guess the readme can address starting an appium server before the run as its usage.

**Comment by KazuCocoa** [comment]
I've added to start an appium instance as https://github.com/KazuCocoa/appium_dart/tree/main/example
Will the step be enough for you?

**Comment by lorenacimpean** [comment]
[Appium] Welcome to Appium v1.22.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

static var localServer = Uri.parse('http://0.0.0.0:4723/wd/hub/');

The following SocketException was thrown running a test:
OS Error: Connection refused, errno = 111, address = 0.0.0.0, port = 58276

I think there's still an issue with the port. Can you reproduce it in your example?
