### ISSUE TITLE
Not able to find WebElement

### ISSUE THREAD

**Issue by mygoa** [KazuCocoa/appium_dart#40]
Hi, 

I need to use appium like selenium for mobile, and I need to access some infos on a website, but I fail to find it. Does AppiumBy works for webpage, right? I know the code manage to go to the webpage. Here's my code:

  late AppiumWebDriver driver;
  driver = await createDriver(
      uri: Uri.parse('http://192.168.1.158:4723/wd/hub/'),
      desired: {
        'platformName': 'Android',
        'platformVersion': '12',
        'deviceName': 'Android Emulator',
        'browserName': 'Chrome',
        'automationName': 'Appium',
      });
  driver.get("https://fr.indeed.com/m/?from=gnav-viewjob");
  AppiumWebElement indeedJobInputField = await driver.findElement(AppiumBy.id("text-input-what"));

Here's my error message: InvalidArgumentException (400): invalid argument: invalid locator

I tried the same webelement with desktop and selenium and it works fine!
If you have any link for web scrapping with dart and appium, you will be my savior!

BR

**Comment by KazuCocoa** [comment]
> I tried the same webelement with desktop and selenium and it works fine!

What does the desktop mean? Does selenium mean with chromedriver etc via this client?


It is by design as `AppiumBy.id` does not convert to CSS internally. Some locators are invalid as Web, but need for Appium native context. So, official selenium clients usually convert id and some locators to CSS internally while this does not do such hack.
https://github.com/KazuCocoa/appium_dart/blob/9a5d3f840620c7003d213d1246f5cb8a703d3172/lib/src/common/by.dart#L7
For web, you need to send locator listed https://w3c.github.io/webdriver/#locator-strategies
